---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    path: charts/prometheus
    targetRevision: HEAD
  # helm:
  #   values: |
  #     # Prometheus chart installs additional dependencies as part of this chart
  #     # to disable any of the additional dependencies set the dependency `enabled`
  #     # to false to disable
  #     alertmanager:
  #       enabled: false
  #     kube-state-metrics:
  #       enabled: false
  #     prometheus-node-exporter:
  #       enabled: false
  #     prometheus-pushgateway
  #       enabled: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prometheus-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true